spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:mysql://172.18.0.2:3306/baton_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: baton123
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
